import { and, desc, eq, sql } from "drizzle-orm";
import { asc } from "drizzle-orm";
import { drizzle } from "drizzle-orm/mysql2";
import { accountSettings, appSettings, blocks, comments, conversationMembers, conversations, follows, likes, messageReads, messageReactions, messages, mutes, notifications, notificationActions, notificationHides, notificationMutes, postHides, postMedia, postShares, posts, reports, saves, stories, storyReactions, storyReplies, users, type InsertUser } from "../drizzle/schema";
import { ENV } from "./_core/env";

let _db: ReturnType<typeof drizzle> | null = null;
export async function getDb() { if (!_db && process.env.DATABASE_URL) { try { _db = drizzle(process.env.DATABASE_URL); } catch (error) { console.warn("[Database] Failed to connect:", error); } } return _db; }

export async function upsertUser(user: InsertUser): Promise<void> {
  if (!user.openId) throw new Error("User openId is required for upsert");
  const db = await getDb(); if (!db) return;
  const values: InsertUser = { openId: user.openId, name: user.name, email: user.email, loginMethod: user.loginMethod, lastSignedIn: user.lastSignedIn ?? new Date(), role: user.role ?? (user.openId === ENV.ownerOpenId ? "admin" : "user") };
  const updateSet: Record<string, unknown> = { lastSignedIn: values.lastSignedIn, name: values.name, email: values.email, loginMethod: values.loginMethod };
  if (user.role) updateSet.role = user.role;
  await db.insert(users).values(values).onDuplicateKeyUpdate({ set: updateSet });
}
export async function getUserByOpenId(openId: string) { const db = await getDb(); if (!db) return undefined; const result = await db.select().from(users).where(eq(users.openId, openId)).limit(1); return result[0]; }
export async function getFeed(limit = 20) { const db = await getDb(); if (!db) return []; return db.select({ post: posts, media: postMedia, author: users }).from(posts).leftJoin(postMedia, eq(postMedia.postId, posts.id)).innerJoin(users, eq(users.id, posts.authorId)).orderBy(desc(posts.createdAt)).limit(limit); }
export async function getProfile(userId: number) { const db = await getDb(); if (!db) return undefined; const result = await db.select().from(users).where(eq(users.id, userId)).limit(1); return result[0]; }
export function buildProfileUpdateNotifications(actorId: number, followerIds: number[]) { return Array.from(new Set(followerIds)).filter(recipientId => recipientId !== actorId).map(recipientId => ({ recipientId, actorId, type: "profile_update" as const, entityId: actorId })); }
export function buildAdminPromotionNotification(actorId: number, targetId: number) { return { recipientId: targetId, actorId, type: "message" as const, entityId: targetId }; }
export async function updateProfile(userId: number, input: Partial<Pick<InsertUser, "username" | "displayName" | "bio" | "website" | "avatarUrl" | "isPrivate">>) { const db = await getDb(); if (!db) return { success: true, notifiedFollowers: 0 }; await db.update(users).set(input).where(eq(users.id, userId)); const followerRows = await db.select({ followerId: follows.followerId }).from(follows).where(and(eq(follows.followingId, userId), eq(follows.status, "accepted"))); const profileNotifications = buildProfileUpdateNotifications(userId, followerRows.map(row => row.followerId)); if (profileNotifications.length) await db.insert(notifications).values(profileNotifications); return { success: true, notifiedFollowers: profileNotifications.length }; }
export async function toggleLike(userId: number, postId: number) { const db = await getDb(); if (!db) return false; const existing = await db.select().from(likes).where(and(eq(likes.userId, userId), eq(likes.postId, postId))).limit(1); if (existing[0]) { await db.delete(likes).where(eq(likes.id, existing[0].id)); return false; } await db.insert(likes).values({ userId, postId }); return true; }
export async function toggleSave(userId: number, postId: number) { const db = await getDb(); if (!db) return false; const existing = await db.select().from(saves).where(and(eq(saves.userId, userId), eq(saves.postId, postId))).limit(1); if (existing[0]) { await db.delete(saves).where(eq(saves.id, existing[0].id)); return false; } await db.insert(saves).values({ userId, postId }); return true; }
export async function createPost(authorId: number, input: { caption?: string; location?: string; hashtags?: string; mentions?: string; audience?: "public" | "followers" | "private"; commentsEnabled?: boolean; media: { url: string; mediaType: "image" | "video"; width?: number; height?: number }[] }) { const db = await getDb(); if (!db) return undefined; const result = await db.insert(posts).values({ authorId, caption: input.caption, location: input.location, hashtags: input.hashtags, mentions: input.mentions, audience: input.audience ?? "public", commentsEnabled: input.commentsEnabled ?? true }); const postId = Number(result[0].insertId); if (input.media.length) await db.insert(postMedia).values(input.media.map((item, index) => ({ postId, ...item, sortOrder: index }))); return postId; }
export async function addComment(authorId: number, postId: number, body: string, parentId?: number) { const db = await getDb(); if (!db) return; await db.insert(comments).values({ authorId, postId, body, parentId }); }
export async function followUser(followerId: number, followingId: number, isPrivate: boolean) { const db = await getDb(); if (!db) return "accepted" as const; await db.insert(follows).values({ followerId, followingId, status: isPrivate ? "pending" : "accepted" }).onDuplicateKeyUpdate({ set: { status: isPrivate ? "pending" : "accepted" } }); return isPrivate ? "pending" as const : "accepted" as const; }
export async function toggleBlock(blockerId: number, blockedId: number) { const db = await getDb(); if (!db) return false; const existing = await db.select().from(blocks).where(and(eq(blocks.blockerId, blockerId), eq(blocks.blockedId, blockedId))).limit(1); if (existing[0]) { await db.delete(blocks).where(eq(blocks.id, existing[0].id)); return false; } await db.insert(blocks).values({ blockerId, blockedId }); return true; }
export async function toggleMute(muterId: number, mutedId: number) { const db = await getDb(); if (!db) return false; const existing = await db.select().from(mutes).where(and(eq(mutes.muterId, muterId), eq(mutes.mutedId, mutedId))).limit(1); if (existing[0]) { await db.delete(mutes).where(eq(mutes.id, existing[0].id)); return false; } await db.insert(mutes).values({ muterId, mutedId }); return true; }
export async function hidePost(userId: number, postId: number) { const db = await getDb(); if (!db) return { success: true }; await db.insert(postHides).values({ userId, postId }).onDuplicateKeyUpdate({ set: { postId } }); return { success: true }; }
export async function sharePost(userId: number, postId: number) { const db = await getDb(); if (!db) return { success: true }; await db.insert(postShares).values({ userId, postId }); return { success: true }; }
export async function getSettings(userId: number) { const db = await getDb(); if (!db) return undefined; const existing = await db.select().from(accountSettings).where(eq(accountSettings.userId, userId)).limit(1); if (existing[0]) return existing[0]; await db.insert(accountSettings).values({ userId }); const created = await db.select().from(accountSettings).where(eq(accountSettings.userId, userId)).limit(1); return created[0]; }
export async function updateSettings(userId: number, input: Partial<typeof accountSettings.$inferInsert>) { const db = await getDb(); if (!db) return; await db.insert(accountSettings).values({ userId, ...input }).onDuplicateKeyUpdate({ set: input }); }
export const defaultAppSettings = { id: 1, appName: "Luna Social", tagline: "Find your people under the same sky.", theme: "dark" as const, accentColor: "#a98cff", logoUrl: null as string | null, updatedBy: null as number | null };
export async function getAppSettings() { const db = await getDb(); if (!db) return defaultAppSettings; const existing = await db.select().from(appSettings).where(eq(appSettings.id, 1)).limit(1); return existing[0] || defaultAppSettings; }
export async function updateAppSettings(updatedBy: number, input: Partial<Pick<typeof appSettings.$inferInsert, "appName" | "tagline" | "theme" | "accentColor" | "logoUrl">>) { const db = await getDb(); if (!db) return { ...defaultAppSettings, ...input, updatedBy }; await db.insert(appSettings).values({ id: 1, ...input, updatedBy }).onDuplicateKeyUpdate({ set: { ...input, updatedBy } }); return getAppSettings(); }
export const notificationActionLabels: Record<string, string> = { approve: "Approved", decline: "Declined", cancel: "Request canceled", mute: "Muted", hide: "Hidden", read: "Marked as read", report: "Reported" };
export async function listNotifications(userId: number) { const db = await getDb(); if (!db) return []; const rows = await db.select({ notification: notifications, action: notificationActions.action }).from(notifications).leftJoin(notificationActions, and(eq(notificationActions.notificationId, notifications.id), eq(notificationActions.userId, userId))).where(eq(notifications.recipientId, userId)).orderBy(desc(notifications.createdAt)).limit(40); return rows.map(row => ({ ...row.notification, action: row.action || null, actionLabel: row.action ? notificationActionLabels[row.action] || row.action : null })); }
export async function recordNotificationAction(userId: number, notificationId: number, action: keyof typeof notificationActionLabels) { const db = await getDb(); if (!db) return { success: true, action }; const notification = await db.select().from(notifications).where(and(eq(notifications.id, notificationId), eq(notifications.recipientId, userId))).limit(1); if (!notification[0]) return { success: false, action }; await db.insert(notificationActions).values({ userId, notificationId, action }).onDuplicateKeyUpdate({ set: { action } }); return { success: true, action }; }
export async function markNotificationRead(userId: number, notificationId: number) { const db = await getDb(); if (!db) return { success: true }; await db.update(notifications).set({ readAt: new Date() }).where(and(eq(notifications.id, notificationId), eq(notifications.recipientId, userId))); return { success: true }; }
export async function hideNotification(userId: number, notificationId: number) { const db = await getDb(); if (!db) return { success: true }; await db.insert(notificationHides).values({ userId, notificationId }).onDuplicateKeyUpdate({ set: { notificationId } }); return { success: true }; }
export async function muteNotificationType(userId: number, notificationType: string) { const db = await getDb(); if (!db) return { success: true }; await db.insert(notificationMutes).values({ userId, notificationType }).onDuplicateKeyUpdate({ set: { notificationType } }); return { success: true }; }
export async function updateFollowStatus(userId: number, actorId: number, status: "accepted" | "declined" | "cancelled") { const db = await getDb(); if (!db) return { success: true }; const whereClause = status === "cancelled" ? and(eq(follows.followerId, userId), eq(follows.followingId, actorId)) : and(eq(follows.followingId, userId), eq(follows.followerId, actorId)); await db.update(follows).set({ status }).where(whereClause); return { success: true }; }
export function normalizeMemberSearchTerm(query: string) { return query.trim().toLowerCase().replace(/^@+/, ""); }
export async function searchMembers(userId: number, query: string) { const db = await getDb(); const term = normalizeMemberSearchTerm(query); if (!db || term.length < 2) return []; return db.select({ id: users.id, name: users.name, displayName: users.displayName, username: users.username, avatarUrl: users.avatarUrl, isPrivate: users.isPrivate }).from(users).where(and(sql`${users.id} <> ${userId}`, sql`lower(concat(coalesce(${users.username}, ''), ' ', coalesce(${users.displayName}, ''), ' ', coalesce(${users.name}, ''))) like ${`%${term}%`}`)).orderBy(users.displayName).limit(12); }
export function isDirectConversationMemberCount(count: number) { return count === 2; }
export async function findOrCreateDirectConversation(userId: number, memberId: number) { if (userId === memberId) throw new Error("You cannot start a conversation with yourself"); const db = await getDb(); if (!db) return { conversationId: 0 }; const mine = await db.select().from(conversationMembers).where(eq(conversationMembers.userId, userId)); for (const membership of mine) { const members = await db.select().from(conversationMembers).where(eq(conversationMembers.conversationId, membership.conversationId)); const peer = members.find(item => item.userId === memberId); if (peer && isDirectConversationMemberCount(members.length)) return { conversationId: membership.conversationId }; } const conversation = await db.insert(conversations).values({}); const conversationId = Number(conversation[0].insertId); await db.insert(conversationMembers).values([{ conversationId, userId }, { conversationId, userId: memberId }]); return { conversationId }; }
export function calculateConversationUnreadCount(messages: Array<{ senderId: number; createdAt: Date | string }>, userId: number, lastReadAt?: Date | string | null) { const readTimestamp = lastReadAt ? new Date(lastReadAt).getTime() : null; return messages.filter(message => message.senderId !== userId && (readTimestamp === null || new Date(message.createdAt).getTime() > readTimestamp)).length; }
export async function listConversationInbox(userId: number) { const db = await getDb(); if (!db) return []; const memberships = await db.select().from(conversationMembers).where(eq(conversationMembers.userId, userId)); const inbox = []; for (const membership of memberships) { const members = await db.select({ member: conversationMembers, user: users }).from(conversationMembers).innerJoin(users, eq(users.id, conversationMembers.userId)).where(eq(conversationMembers.conversationId, membership.conversationId)); const other = members.find(item => item.member.userId !== userId); const conversationMessages = await db.select().from(messages).where(eq(messages.conversationId, membership.conversationId)).orderBy(desc(messages.createdAt)); const last = conversationMessages[0]; const unreadCount = calculateConversationUnreadCount(conversationMessages, userId, membership.lastReadAt); if (other) inbox.push({ conversation: membership.conversationId, member: other.user, lastMessage: last || null, lastReadAt: membership.lastReadAt, unreadCount }); } return inbox; }
export async function listMessages(userId: number, conversationId?: number) { const db = await getDb(); if (!db) return []; let rows; if (conversationId) { const membership = await db.select().from(conversationMembers).where(and(eq(conversationMembers.conversationId, conversationId), eq(conversationMembers.userId, userId))).limit(1); if (!membership[0]) return []; rows = await db.select().from(messages).where(eq(messages.conversationId, conversationId)).orderBy(messages.createdAt).limit(200); } else { const memberships = await db.select().from(conversationMembers).where(eq(conversationMembers.userId, userId)); if (!memberships.length) return []; rows = await db.select().from(messages).where(eq(messages.senderId, userId)).orderBy(messages.createdAt).limit(200); } return Promise.all(rows.map(async row => { const [reaction, read] = await Promise.all([db.select().from(messageReactions).where(and(eq(messageReactions.messageId, row.id), eq(messageReactions.userId, userId))).limit(1), db.select().from(messageReads).where(and(eq(messageReads.messageId, row.id), eq(messageReads.userId, userId))).limit(1)]); return { ...row, reaction: reaction[0]?.reaction || null, readAt: read[0]?.readAt || null }; })); }
export async function reactToMessage(userId: number, messageId: number, reaction: string) { const db = await getDb(); if (!db) return { success: true, reaction }; const message = await db.select().from(messages).where(eq(messages.id, messageId)).limit(1); if (!message[0]) return { success: false, reaction: "" }; const membership = await db.select().from(conversationMembers).where(and(eq(conversationMembers.conversationId, message[0].conversationId), eq(conversationMembers.userId, userId))).limit(1); if (!membership[0]) return { success: false, reaction: "" }; if (!reaction) await db.delete(messageReactions).where(and(eq(messageReactions.messageId, messageId), eq(messageReactions.userId, userId))); else await db.insert(messageReactions).values({ messageId, userId, reaction }).onDuplicateKeyUpdate({ set: { reaction } }); return { success: true, reaction }; }
export async function markMessagesRead(userId: number, conversationId: number) { const db = await getDb(); if (!db) return { success: true }; const membership = await db.select().from(conversationMembers).where(and(eq(conversationMembers.conversationId, conversationId), eq(conversationMembers.userId, userId))).limit(1); if (!membership[0]) return { success: false }; const unread = await db.select().from(messages).where(eq(messages.conversationId, conversationId)); for (const message of unread) { await db.insert(messageReads).values({ messageId: message.id, userId }).onDuplicateKeyUpdate({ set: { readAt: new Date() } }); } await db.update(conversationMembers).set({ lastReadAt: new Date() }).where(and(eq(conversationMembers.conversationId, conversationId), eq(conversationMembers.userId, userId))); return { success: true }; }
export async function sendMessage(senderId: number, conversationId: number, body: string, attachmentUrl?: string, attachmentType?: "image" | "video" | "voice") { const db = await getDb(); if (!db) return { id: Date.now(), conversationId, senderId, body, attachmentUrl, attachmentType, createdAt: new Date() }; const membership = await db.select().from(conversationMembers).where(and(eq(conversationMembers.conversationId, conversationId), eq(conversationMembers.userId, senderId))).limit(1); if (!membership[0]) throw new Error("You are not a member of this conversation"); const result = await db.insert(messages).values({ senderId, conversationId, body, attachmentUrl, attachmentType }); return { id: Number(result[0].insertId), conversationId, senderId, body, attachmentUrl, attachmentType, createdAt: new Date() }; }
export async function createReport(reporterId: number, input: { postId?: number; commentId?: number; reportedUserId?: number; reason: string; details?: string }) { const db = await getDb(); if (!db) return; await db.insert(reports).values({ reporterId, ...input }); }
export async function listReports(limit = 20) { const db = await getDb(); if (!db) return []; return db.select().from(reports).orderBy(desc(reports.createdAt)).limit(limit); }
export async function createStory(authorId: number, mediaUrl: string, mediaType: "image" | "video", caption?: string) { const expiresAt = new Date(Date.now() + 24 * 60 * 60 * 1000); const db = await getDb(); if (!db) return { id: Date.now(), expiresAt }; const result = await db.insert(stories).values({ authorId, mediaUrl, mediaType, caption, expiresAt }); return { id: Number(result[0].insertId), expiresAt }; }
export async function listStories() { const db = await getDb(); if (!db) return []; return db.select({ story: stories, author: users }).from(stories).innerJoin(users, eq(users.id, stories.authorId)).where(sql`${stories.expiresAt} > NOW()`).orderBy(desc(stories.createdAt)); }
export async function reactToStory(userId: number, storyId: number, reaction: string) { const db = await getDb(); if (!db) return { success: true }; await db.insert(storyReactions).values({ userId, storyId, reaction }).onDuplicateKeyUpdate({ set: { reaction } }); return { success: true }; }
export async function replyToStory(authorId: number, storyId: number, body: string) { const db = await getDb(); if (!db) return { success: true }; await db.insert(storyReplies).values({ authorId, storyId, body }); return { success: true }; }

export async function listMembersWithRoles(query = "") {
  const db = await getDb();
  const normalized = query.trim().toLowerCase();
  if (!db) return [];
  const pattern = `%${normalized}%`;
  return db.select({ id: users.id, name: users.name, username: users.username, displayName: users.displayName, role: users.role, avatarUrl: users.avatarUrl, createdAt: users.createdAt }).from(users).where(normalized ? sql`(LOWER(COALESCE(${users.username}, '')) LIKE ${pattern} OR LOWER(COALESCE(${users.displayName}, '')) LIKE ${pattern} OR LOWER(COALESCE(${users.name}, '')) LIKE ${pattern})` : undefined).orderBy(asc(users.createdAt)).limit(100);
}

export async function searchAdminUsers(query: string) {
  const db = await getDb();
  const normalized = query.trim().toLowerCase();
  if (!db || normalized.length < 2) return [];
  const pattern = `%${normalized}%`;
  return db.select({ id: users.id, name: users.name, username: users.username, displayName: users.displayName, role: users.role, avatarUrl: users.avatarUrl }).from(users).where(sql`(LOWER(COALESCE(${users.username}, '')) LIKE ${pattern} OR LOWER(COALESCE(${users.displayName}, '')) LIKE ${pattern} OR LOWER(COALESCE(${users.name}, '')) LIKE ${pattern})`).limit(25);
}

export async function promoteSelectedUser(actorId: number, targetId: number, role: "admin" | "user" = "admin") {
  const db = await getDb();
  if (!db || actorId === targetId) return { success: false as const, reason: "invalid_target" as const };
  const [target] = await db.select({ id: users.id, role: users.role }).from(users).where(eq(users.id, targetId)).limit(1);
  if (!target) return { success: false as const, reason: "not_found" as const };
  await db.update(users).set({ role }).where(eq(users.id, targetId));
  if (role === "admin") await db.insert(notifications).values(buildAdminPromotionNotification(actorId, targetId));
  return { success: true as const, userId: targetId, role };
}
